/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package;

import java.text.DecimalFormat;

/**
 *
 * @author Kenia Martinez
 */
public class Docentes extends javax.swing.JFrame {

    /**
     * Creates new form Docentes
     */
    public Docentes() {
        initComponents();
    }
    
    cls_Docente docente = new cls_Docente();
    DecimalFormat nd = new DecimalFormat("#.00");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        lblIdentidad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAnios = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jsClase = new javax.swing.JSpinner();
        txtPagoClase = new javax.swing.JTextField();
        rbRenuncia = new javax.swing.JRadioButton();
        rbDespido = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        lblPreavisoRealizado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rbNo = new javax.swing.JRadioButton();
        rbSi = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLEADOS - DOCENTE");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setName("frameDocentes"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DOCENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 204));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Identidad:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 40, 54, -1));

        lblIdentidad.setText("-");
        lblIdentidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel1.add(lblIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 215, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DATOS PERSONALES");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, -1, -1));

        lblNombre.setText("-");
        lblNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 39, 215, -1));

        jLabel11.setText("Nombre:");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 40, 54, -1));

        jLabel2.setText("Años laborados:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        lblAnios.setText("-");
        panel1.add(lblAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 664, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PAGO POR CLASE");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel7.setText("Pago por Clase:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 110, -1));

        jsClase.setModel(new javax.swing.SpinnerNumberModel(1, 1, 25, 1));
        jsClase.setAutoscrolls(true);
        jPanel1.add(jsClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        txtPagoClase.setText("0");
        jPanel1.add(txtPagoClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 90, -1));

        buttonGroup1.add(rbRenuncia);
        rbRenuncia.setText("Renuncia");
        rbRenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRenunciaActionPerformed(evt);
            }
        });
        jPanel1.add(rbRenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, -1));

        buttonGroup1.add(rbDespido);
        rbDespido.setText("Despido");
        rbDespido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDespidoActionPerformed(evt);
            }
        });
        jPanel1.add(rbDespido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel8.setText("Número de Clases:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        lblPreavisoRealizado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPreavisoRealizado.setText("¿Realizó preaviso?");
        jPanel1.add(lblPreavisoRealizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, 20));

        btnCalcular.setText("Mostrar Resumen");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("MOTIVO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 20));

        buttonGroup2.add(rbNo);
        rbNo.setText("No");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 50, -1));

        buttonGroup2.add(rbSi);
        rbSi.setText("Si");
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });
        jPanel1.add(rbSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 660, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbDespidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDespidoActionPerformed
        // TODO add your handling code here:
        if(rbDespido.isSelected()){
            lblPreavisoRealizado.setVisible(true);
            rbNo.setVisible(true);
            rbSi.setVisible(true);
            //rbRenuncia.setEnabled(false);
        }
    }//GEN-LAST:event_rbDespidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblPreavisoRealizado.setVisible(false);
        rbNo.setVisible(false);
        rbSi.setVisible(false);
        btnCalcular.setVisible(false);
        //panelPrestaciones.setVisible(false);
        lblNombre.setText(docente.getNombre());
        lblIdentidad.setText(docente.getIdentidad());
        lblAnios.setText("" +docente.getAntiguedad());
    }//GEN-LAST:event_formWindowOpened

    private void rbRenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRenunciaActionPerformed
        // TODO add your handling code here:
        if (rbRenuncia.isSelected()) {
            btnCalcular.setVisible(true);
            //panelPrestaciones.setVisible(true);
            //rbDespido.setEnabled(false);
            rbSi.setVisible(false);
            rbNo.setVisible(false);
            lblPreavisoRealizado.setVisible(false);
        }
    }//GEN-LAST:event_rbRenunciaActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed
        // TODO add your handling code here:
        if (rbSi.isSelected()) {
            btnCalcular.setVisible(true);
            //panelPrestaciones.setVisible(true);
            //rbNo.setEnabled(false);
        }
    }//GEN-LAST:event_rbSiActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        // TODO add your handling code here:
        if (rbNo.isSelected()) {
            btnCalcular.setVisible(true);
            //panelPrestaciones.setVisible(true);
            //rbSi.setEnabled(false);
        }
    }//GEN-LAST:event_rbNoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        docente.setNumClases(Integer.parseInt(jsClase.getValue().toString()));
        docente.setPagoClase(Double.parseDouble(txtPagoClase.getText()));
        
        docente.CalcularSueldo();
        docente.CalculoDecimo();
        docente.CalculoAguinaldo();
        
        if(rbRenuncia.isSelected()){
            docente.setMotivo(rbRenuncia.getName());
            
            docente.setCesantia(0);
            docente.setPreaviso(0);
        }
        
        if(rbDespido.isSelected() && rbNo.isSelected()){
            docente.setMotivo(rbDespido.getName());
            docente.CalculoCesantia();
            docente.CalculoPreaviso();
            docente.CalculoDecimo();
        }
        
        if(rbDespido.isSelected() && rbSi.isSelected()){
            docente.setMotivo(rbDespido.getName());
            docente.CalculoCesantia();
            docente.setPreaviso(0);
            docente.CalculoDecimo();
        }
        MostrarDatos datos = new MostrarDatos();
        datos.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Docentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jsClase;
    private javax.swing.JLabel lblAnios;
    private javax.swing.JLabel lblIdentidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPreavisoRealizado;
    private java.awt.Panel panel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JRadioButton rbDespido;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbRenuncia;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTextField txtPagoClase;
    // End of variables declaration//GEN-END:variables
}
